faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
    path('Add/', views.Add, name='Add'),
    path('Delete/<pk>/', views.Delete, name='Delete'),
    path('Edit/<int:idx>/', views.Edit, name='Edit'),

]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('faq/', include('faq.urls')),
    path('hoaxbuster/', include('hoaxbuster.urls')),
    path('penanganan/', include('penanganan.urls')),
    path('userauth/', include('userauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/models.py
from django.db import models

# Create your models here.
class FAQContent(models.Model):
    judul = models.TextField()
    isi = models.TextField()

    def __str__(self):
        return self.judul

faq/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from .models import *
from .FAQForm import Content
from django.template.loader import render_to_string

from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
     form = Content()
     contents = FAQContent.objects.all()

     return render(request, 'faq/index.html', {'forms' : form , 'contents' : contents})

#@login_required(login_url="tk2/userauth/")
def Add(request):
    form = Content()
    if request.is_ajax and request.method == 'POST':
        form = Content(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect('/')
        else:
            # some form errors occured.
            return JsonResponse({"error": form.errors}, status=400)

    return render(request, 'faq/Add.html',{'form' : form})

#@login_required(login_url="tk2/userauth/")
def Delete(request, pk):
    konten = FAQContent.objects.filter(id=pk)
    judul = FAQContent.objects.get(id= pk)
    if request.method =='POST':
        konten.delete()
        return redirect('/faq/')
    context = {'form':konten}
    return render(request, 'faq/index.html' , context)

#@login_required(login_url="tk2/userauth/")
def Edit(request, idx):
    content = FAQContent.objects.get(id=idx)
    form = Content(instance=content)

    context= {'form': form}

    if request.method == 'POST': 
        form = Content(request.POST, request.FILES, instance=content)
  
        if form.is_valid():
            form.save()
        
        return redirect('/faq/')

    return render(request, 'faq/Edit.html', context)

def data(request):
    url = "https://faq.coronavirus.gov/api/v2/questions.json"
    ret = requests.get(url)

    contentData = json.loads(ret.content)
    return JsonResponse(contentData, safe = False)

    

faq/templates/faq/Add.html
{% extends 'template.html' %}

{% block title %}
Add
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'faq/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$("#addform").ready(function(){
  $("#addform").submit(function(){
    alert("Konten telah ditambahkan");
  });
});

$("#addForm").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
            type: 'POST',
            data: serializedData,
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#friend-form").trigger('reset');
            }
        });
    });
</script>

{% endblock head %}

{% block body %}
    <div>
        <div class="row blank"></div>
        <div class="row justify-content-center">
            <h1 style="text-align: center;">Add Content</h1>
        </div>
    
        <div class="row justify-content-center">
            <div class="table-responsive-lg">
                <form action="" method="POST" enctype="multipart/form-data">
                <table class="table form" style="margin-right: 7vw;">
                    <tbody class="form">
                        <form id = "addForm">
                        {{ form.as_table }}
                        <tr>
                            <td colspan="2" style="text-align: center;">
                                {% csrf_token %}
                                <input class="btn btn-info" type="submit" value="Add Content" style="padding-right: 50px; padding-left: 50px;">
                            </td>
                        </tr>
                    </form>
                    </tbody>
                </table>
                </form>
            </div>
        </div>
        
        <div class="row blank"></div>
    
    </div>

{% endblock body %}

faq/templates/faq/Edit.html
{% extends 'template.html' %}

{% block title %}
Edit
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'faq/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("form").submit(function(){
    alert("Konten telah diedit");
    var d = new Date();
    document.getElementById("demo").innerHTML = d;
    console.log(d);
  });
});
</script>

{% endblock head %}

{% block body %}
    <div>
        <div class="row blank"></div>
        <div class="row justify-content-center">
            <h1 style="text-align: center;">Edit Content</h1>
        </div>
    
        <div class="row justify-content-center">
            <div class="table-responsive-lg">
                <form action="" method="POST" enctype="multipart/form-data">
                <table class="table form" style="margin-right: 7vw;">
                    <tbody>
                        {{ form.as_table }}
                        <tr>
                            <td colspan="2" style="text-align: center;">
                                {% csrf_token %}
                                <input class="btn btn-info" type="submit" value="Edit Content" style="padding-right: 3vw; padding-left: 3vw;">
                            </td>
                        </tr>
                    </tbody>
                </table>
                </form>
            </div>
        </div>
        
        <div class="row blank"></div>
    
    </div>
{% endblock body %}

faq/templates/faq/contentnobutton.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  $(document).ready(function(){
  $("#slidebutton1,#slidebutton2").click(function(){
    $("p").slideToggle();
  });
});
</script>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin: 10vh 10vw 10vh 10vw;">
    <div class="carousel-inner">
      {% for i in contents %}
      {% if forloop.first %}
      <div class="carousel-item active">
        <div class="d-flex align-items-center justify-content-center min-vh-30">
            <h2>{{i.judul}}</h2>
          </div>
          <div class="d-flex align-items-center justify-content-center" style="min-height: 50vh;">
          <p>{{i.isi}} {{ field.contents|linebreaksbr }}</p>
          <div>
            <button id="slidebutton1">More</button>
          </div>
        </div>
      </div>  
      {% else %}
      <div class="carousel-item">
        <div class="d-flex align-items-center justify-content-center min-vh-30">
          <h2>{{i.judul}}</h2>
        </div>
        <div class="d-flex align-items-center justify-content-center" style="min-height: 50vh;">
        <p>{{i.isi}} {{ field.contents|linebreaksbr }}</p>
        <div>
          <button id="slidebutton2">More</button>
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    </div>
  </div>

faq/templates/faq/contentwithbutton.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/js/moment.min.js"></script>

<script>
$("#del").ready(function(){
  $("form").submit(function(){
      alert("Konten telah dihapus");
  });
  $("#del").click( function(event) {
    
        if ($(event.target).hasClass('del btn-danger')) {
            $.ajax({
                type: "GET",
                success: function(response){
                    $("#del").html(response.update);
                }
            });
        }
    });
});

$(document).ready(function(){
  $("#slidebutton1,#slidebutton2").click(function(){
    $("p").slideToggle();
  });
});

var x = document.lastModified;
$('#date').append("Last Modified" + x);


</script>



<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin: 10vh 10vw 10vh 10vw;">
  <div class="carousel-inner">
    <div class="d-flex flex-row">
    <div class="p-2">
      <button class="btn btn-success" type="button" onclick="window.location.href='{% url 'faq:Add' %}'">Add</button>
    </div>
  </div>
      {% for i in contents %}
      {% if forloop.first %}
      <div class="carousel-item active">
        <div class="d-flex flex-row">
          
          <div class="p-2">
            <button  class="btn btn-success" type="button" onclick="window.location.href='{% url 'faq:Edit' i.id %}'">Edit</button>
          </div>
          <div class="p-2">
            <form action="{% url 'faq:Delete' i.id %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-danger" type = "submit" value="Delete">
            </form>
          </div>
        </div>
        <div class="d-flex align-items-center justify-content-center min-vh-30">
            <h2>{{i.judul}}</h2>
          </div>
          <div class="d-flex align-items-center justify-content-center" style="min-height: 50vh;">
          <p>{{i.isi}} {{ field.contents|linebreaksbr }}</p>
          <div>
          <button id="slidebutton1">More</button>
        </div>
        </div>
      </div>
      {% else %}
      <div class="carousel-item">
        <div class="d-flex flex-row">
          <div class="p-2">
            <button  class="btn btn-success" type="button" onclick="window.location.href='{% url 'faq:Edit' i.id %}'">Edit</button>
          </div>
          <div class="p-2">
            <form id="del" action="{% url 'faq:Delete' i.id %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-danger" type = "submit" value="Delete">
            </form>
          </div>
        </div>
        <div class="d-flex align-items-center justify-content-center min-vh-30">
          <h2>{{i.judul}}</h2>
        </div>
        <div class="d-flex align-items-center justify-content-center" style="min-height: 50vh;">
        <p>{{i.isi}} {{ field.contents|linebreaksbr }}</p>
        <div>
          <button id="slidebutton2">More</button>
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    </div>
    </div>

faq/templates/faq/index.html
{% extends 'template.html' %}

{% block title %}
FAQ
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'faq/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% endblock head %}

{% block styling %}
{% endblock styling %}

{% block body %}
{% if user.is_authenticated %}
{% include 'faq/contentwithbutton.html' %}
{% else %}
{% include 'faq/contentnobutton.html' %}
{% endif %}
{% endblock body %}