faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
    path('Add/', views.Add, name='Add'),
    path('Delete/<pk>/', views.Delete, name='Delete'),
    path('Edit/<int:idx>/', views.Edit, name='Edit'),

]

penanganan/urls.py
from django.urls import path

from . import views

app_name = 'penanganan'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('delete/<int:id>', views.delete, name='delete')
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('faq/', include('faq.urls')),
    path('hoaxbuster/', include('hoaxbuster.urls')),
    path('penanganan/', include('penanganan.urls')),
    path('userauth/', include('userauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

penanganan/models.py
from django.db import models

# Create your models here.
class RumahSakit(models.Model):
    nama = models.CharField(max_length=40)
    hp = models.CharField(max_length=40)
    alamat = models.CharField(max_length=1024)
    provinsi = models.CharField(max_length=40)

penanganan/forms.py
from django import forms

LIST_PROVINSI = [
    ('aceh', 'Aceh'),
    ('bali', 'Bali'),
    ('banten', 'Banten'),
    ('bengkulu', 'Bengkulu'),
    ('gorontalo', 'Gorontalo'),
    ('jakarta', 'Jakarta'),
    ('jambi', 'Jambi'),
    ('jawa_barat', 'Jawa Barat'),
    ('jawa_tengah', 'Jawa Tengah'),
    ('jawa_timur', 'Jawa Timur'),
    ('kalimantan_barat', 'Kalimantan Barat'),
    ('kalimantan_timur', 'Kalimantan Timur'),
    ('kalimantan_utara', 'Kalimantan Utara'),
    ('bangka_belitung', 'Bangka Belitung'),
    ('riau', 'Riau'),
    ('maluku', 'Maluku'),
    ('maluku_utara', 'Maluku_utara'),
    ('ntb', 'Nusa Tenggara Barat'),
    ('ntt', 'Nusa Tenggara Timur'),
    ('papua', 'Papua'),
    ('papua_barat', 'Papua Barat'),
    ('sulawesi_barat', 'Sulawesi Barat'),
    ('sulawesi_selatan', 'Sulawesi Selatan'),
    ('sulawesi_tengah', 'Sulawesi Tengah'),
    ('sulawesi_tenggara', 'Sulawesi Tenggara'),
    ('sumatra_barat', 'Sumatra Barat'),
    ('sumatra_selatan', 'Sumatra Selatan'),
    ('sumatra_utara', 'Sumatra Utara'),
    ('yogyakarta', 'Yogyakarta'),
    ]

class FormRS(forms.Form):
    nama = forms.CharField(label="Nama")
    hp = forms.CharField(label="Nomor HP")
    alamat = forms.CharField(label="Alamat")
    provinsi = forms.CharField(label="Provinsi" ,widget=forms.Select(choices=LIST_PROVINSI))

class FormProvinsi(forms.Form):
    provinsi = forms.CharField(label="", widget=forms.Select(choices=LIST_PROVINSI))

penanganan/views.py
from django.shortcuts import render, redirect
from .models import RumahSakit
from .forms import FormRS, FormProvinsi

# Create your views here.

def index(request):
    if request.method == "POST":
        form = FormProvinsi(request.POST)
        if form.is_valid():
            provinsi = form.cleaned_data['provinsi']
            list_rumah_sakit = RumahSakit.objects.filter(provinsi = provinsi)
            context = {
                'list_rumah_sakit' : list_rumah_sakit,
                'form' : FormProvinsi()}

            return render(request, 'penanganan/index.html', context)
    
    else:
        form = FormProvinsi()
        return render(request, 'penanganan/index.html', {'form' : form})

def rumah_sakit(request):
    list_rumah_sakit = RumahSakit.objects.all().filter(provinsi = request.POST['provinsi'])
    
    context =   {"list_rumah_sakit" : list_rumah_sakit}

    return render(request, 'penanganan/rumah_sakit.html', context)

def add(request):
    if request.method == "POST":
        form = FormRS(request.POST)
        if form.is_valid():
            nama = form.cleaned_data['nama']
            hp = form.cleaned_data['hp']
            alamat = form.cleaned_data['alamat']
            provinsi = form.cleaned_data['provinsi']

            newRS = RumahSakit(nama=nama, hp=hp, alamat=alamat, provinsi=provinsi)
            newRS.save()

            return redirect('../')
    
    else:
        form = FormRS()

        return render(request, 'penanganan/add.html', {"form" : form})

def delete(request, id):
    if request.method == "GET":
        rumah_sakit = RumahSakit.objects.get(id = id)
        rumah_sakit.delete()

        return redirect('../')
    
    return redirect('../')

penanganan/templates/penanganan/add.html
<!DOCTYPE html>

{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<style>
.container {
    margin: 50px auto;
    color: #0D98BA;
    display: flex;
    align-items: center;
    flex-direction: column;
}

h2 {
    margin: 20px 0px;
}
</style>

<body>
    <div class='container'>
        <h2>Tambah Rumah Sakit di Provinsi Anda</h2><hr>
        <form action = '' method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' name='tambah' class="btn btn-success">Tambah</button>
        </form>
    </div>
</body>


</html>

penanganan/templates/penanganan/index.html
{% extends 'template.html' %}

{% block title %}
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'penanganan/style.css' %}">


{% endblock head %}

{% block styling %}
{% endblock styling %}

{% block body %}
<div class="container">
    <h2>Apa saja gejala yang timbul jika kita mengidap virus Covid-19 ?</h2>
        <p>Gejala yang timbulkan biasanya ringan. Beberapa orang yang terinfeksi hanya memiliki gejala ringan yang timbul atau tidak sama sekali.</p>
        <ul>
            <li>Indra perasa atau bau kurang sensitif</li>
            <li>Hidung tersumbat</li>
            <li>Sakit tenggorokan</li>
            <li>Sakit kepala</li>
            <li>Nyeri otot atau sendi</li>
            <li>Mual atau muntah</li>
            <li>Diare</li>
            <li>Menggigil atau pusing</li>
        </ul>
        <hr>
        
    <h2>Jika saya mengalami gejala diatas, apa yang harus dilakukan ?</h2>
        <p>Jika anda merasakan beberapa gejala diatas, hal pertama yang harus dilakukan adalah tetap tenang dan jaga kebersihan. Setelah itu lakukan beberapa opsi sebagai berikut:</p>
        <ul>
            <li>Isolasi Mandiri di rumah selama 2 minggu</li>
            <li>Pada saat isolasi, jangan keluar rumah seperti ke kantor, atau ke tempat umum lainnya</li>
            <li>Memisahkan diri dari anggota keluarga yang lain untuk sementara</li>
            <li>Memonitor diri selama 2 minggu. Jika gejala sudah membaik dalam kurun waktu tersebut, tetap jaga kebersihan dan menerapkan protokol kesehatan jika perlu pergi keluar rumah</li>
        </ul>
        <hr>
        
    <h2>Rumah Sakit Rujukan Covid-19 berdasarkan Provinsi</h2>
    <div class='rumahSakit'>
        <div class = 'control'>
            <form action = '' method="POST" class="form-group">
                {% csrf_token %}
                {{ form }}<br>
                <button type='submit' name='check' class="btn btn-success">Check</button>
            </form>
            <a href="{% url 'penanganan:add' %}" class="btn btn-success">Tambah RS</a>
        </div>
        
        <div class="content">
            <ul>
                {% for item in list_rumah_sakit %}
                <li>
                    <b style="color: #0D98BA">{{ item.nama }}</b><br>
                    telp: {{ item.hp }}<br>
                    alamat: {{ item.alamat }}<br>
                    <a href="{% url 'penanganan:delete' id=item.id %}" class="btn btn-danger">Hapus RS</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
        
</div>

{% endblock body %}