faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
    path('Add/', views.Add, name='Add'),
    path('Delete/<pk>/', views.Delete, name='Delete'),
    path('Edit/<int:idx>/', views.Edit, name='Edit'),

]

hoaxbuster/urls.py
from django.urls import path

from . import views

app_name = 'hoaxbuster'

urlpatterns = [
    path('', views.index, name='index'),
    path('addinfo', views.addinfo, name='addinfo'),
    path('deleteinfo/<int:info_id>', views.deleteinfo, name='deleteinfo'),
    path('updateinfo/<int:info_id>', views.updateinfo, name='updateinfo'),
    path('data/', views.data, name='data'),
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('faq/', include('faq.urls')),
    path('hoaxbuster/', include('hoaxbuster.urls')),
    path('penanganan/', include('penanganan.urls')),
    path('userauth/', include('userauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoaxbuster/models.py
from django.db import models

# Create your models here.

class Info(models.Model):
    hoax = models.TextField()
    fakta = models.TextField()
    image = models.ImageField(default="default.png", blank=True)

hoaxbuster/forms.py
from django.forms import ModelForm
from .models import Info

class InfoForm(ModelForm):
    class Meta:
        model = Info
        fields = '__all__'

hoaxbuster/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string

from .models import Info
from .forms import InfoForm

import requests
import json

# Create your views here.

def index(request):
    form = InfoForm()
    update = render_to_string('hoaxbuster/infonobutton.html', {'infos' : Info.objects.all()})

    if request.user.is_authenticated:
        update = render_to_string('hoaxbuster/info.html', {'infos' : Info.objects.all()})

    context = {'info' : update, 'form' : form}
    
    return render(request, 'hoaxbuster/index.html', context)

def updateinfo(request, info_id):
    info = Info.objects.get(id=info_id)
    form = InfoForm(instance=info)
    context = {'form' : form}

    if request.method == 'POST':
        form = InfoForm(request.POST, request.FILES, instance=info)
  
        if form.is_valid():
            form.save()
        
        return redirect('/hoaxbuster/')

    return render(request, 'hoaxbuster/updateinfo.html', context)

def addinfo(request):
    form = InfoForm()
    context = {'form' : form}

    if request.method == 'POST':
        form = InfoForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
        
        update = render_to_string('hoaxbuster/infonobutton.html', {'infos' : Info.objects.all()})

        if request.user.is_authenticated:
            update = render_to_string('hoaxbuster/info.html', {'infos' : Info.objects.all()})

        return JsonResponse({'update' : update})
        # return redirect('/hoaxbuster/')

    # return render_to_string('hoaxbuster/info.html', {'infos' : Info.objects.all()})
    return render(request, 'hoaxbuster/addinfo.html', context)

def deleteinfo(request, info_id):
    info = Info.objects.get(id=info_id)
    info.delete()

    update = render_to_string('hoaxbuster/infonobutton.html', {'infos' : Info.objects.all()})

    if request.user.is_authenticated:
        update = render_to_string('hoaxbuster/info.html', {'infos' : Info.objects.all()})

    return JsonResponse({'update' : update})

def data(request):
    url = "https://factchecktools.googleapis.com/v1alpha1/claims:search?languageCode=" + request.GET['l'] + "&query=" + request.GET['q'] + "&key=AIzaSyD__RG_NfDmqJ8o9Yqr5qefnrw8R7QEyyQ"
    ret = requests.get(url)

    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

hoaxbuster/templates/hoaxbuster/addinfo.html
{% extends 'navbar.html' %}

{% block title %}
Hoaxbuster - Add Info
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
#id_hoax, #id_fakta {
    width: 350px;
    height: 100px;
}
{% endblock styling %}

{% block content %}

<div class="container">
    <div class="row blank"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST" enctype="multipart/form-data">
            <table class="table form">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            {% csrf_token %}
                            <input class="btn btn-info" type="submit" value="Add Info" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

hoaxbuster/templates/hoaxbuster/index.html
{% extends 'template.html' %}

{% block title %}
Hoaxbuster
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
{% endblock styling %}

{% block body %}

<div class="container">
    <div class="row blank"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    {% if info %}

    <div class="row justify-content-center">
        <table class="table table-hover info" style="width: 80%;">
            <thead>
                <tr>
                    <th scope="col" style="width: 150px;"></th>
                    <th scope="col" style="text-align: center;">Hoax</th>
                    <th scope="col" style="text-align: center;">Fakta</th>
                    
                    {% if user.is_authenticated %}
                    <th scope="col" style="width: 150px;"></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody id="info">
    
            {{ info }}
    
            </tbody>
        </table>
    </div>

    {% endif %}

    {% if user.is_authenticated %}
    <div class="row justify-content-center">
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModalCenter" style="padding: 7px 50px 7px 50px;">
            Add Info
        </button>
    </div>
      
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" style="width: fit-content;">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Info</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <form id="info-form" action="" method="POST" enctype="multipart/form-data">
                    <table class="table form">
                        <tbody>
                            {{ form.as_table }}
                            <tr>
                                <td colspan="2" style="text-align: center;">
                                    <p id="message" style="margin: 0; padding: 0;"></p>
                                    {% csrf_token %}
                                    <input class="btn btn-info" type="submit" value="Add Info" style="padding-right: 50px; padding-left: 50px;">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    
    <div class="row blank"></div>

    <div class="row justify-content-center w-75 center">
        <div class="col-3 form-group">
            <select class="form-control" id="language">
                <option value="en">English</option>
                <option value="id">Indonesia</option>
            </select>
        </div>

        <div class="col-9">
            <input id="keyword" class="form-control" placeholder="Enter Keyword">
        </div>

        <div class="w-100"></div>

        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" style="width: 20%;">Publisher</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody id="search-result"></tbody>
            </table>
        </div>
    </div>
    <div class="row blank"></div>
</div>

{% endblock body %}

{% block script %}
<script src="{% static 'hoaxbuster/script.js' %}"></script>
{% endblock script %}

hoaxbuster/templates/hoaxbuster/info.html
{% for info in infos %}
<tr>
    <th scope="row">
        <img src="{{ info.image.url }}" style="width: 150px; height: 150px; border-radius: 50%;">
    </th>
    <td style="text-align: center;">{{ info.hoax }}</td>
    <td style="text-align: center;">{{ info.fakta }}</td>
    
    <td>
        <form action="/hoaxbuster/updateinfo/{{ info.id }}" method="GET" style="display: inline;">
            <input class="btn btn-success" type="submit" value="Update" style="width: 100%; margin: 2px;">
        </form>
        <br>
        <button class="btn btn-danger mybutton del-btn" value="{{ info.id }}">Delete</button>
    </td>
</tr>
{% endfor %}

hoaxbuster/templates/hoaxbuster/infonobutton.html
{% for info in infos %}
<tr>
    <th scope="row">
        <img src="{{ info.image.url }}" style="width: 150px; height: 150px; border-radius: 50%;">
    </th>
    <td style="text-align: center;">{{ info.hoax }}</td>
    <td style="text-align: center;">{{ info.fakta }}</td>
</tr>
{% endfor %}

hoaxbuster/templates/hoaxbuster/updateinfo.html
{% extends 'navbar.html' %}

{% block title %}
Hoaxbuster - Update Info
{% endblock title %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'hoaxbuster/style.css' %}">

{% endblock head %}

{% block styling %}
#id_hoax, #id_fakta {
    width: 350px;
    height: 100px;
}
{% endblock styling %}

{% block content %}

<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h1 class="title">Hoax Buster</h1>
    </div>

    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST" enctype="multipart/form-data">
            <table class="table form">
                <tbody>
                    {% csrf_token %}
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            <input class="btn btn-info" type="submit" value="Update Info" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>

</div>

{% endblock content %}