faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
    path('Add/', views.Add, name='Add'),
    path('Delete/<pk>/', views.Delete, name='Delete'),
    path('Edit/<int:idx>/', views.Edit, name='Edit'),

]

hoaxbuster/urls.py
from django.urls import path

from . import views

app_name = 'hoaxbuster'

urlpatterns = [
    path('', views.index, name='index'),
    path('addinfo', views.addinfo, name='addinfo'),
    path('deleteinfo/<int:info_id>', views.deleteinfo, name='deleteinfo'),
    path('updateinfo/<int:info_id>', views.updateinfo, name='updateinfo'),
    path('data/', views.data, name='data'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('updateData/', views.indexubah, name='indexubah'),
]

penanganan/urls.py
from django.urls import path

from . import views

app_name = 'penanganan'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('delete/<int:id>', views.delete, name='delete')
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('faq/', include('faq.urls')),
    path('hoaxbuster/', include('hoaxbuster.urls')),
    path('penanganan/', include('penanganan.urls')),
    path('userauth/', include('userauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path

from . import views

app_name = 'userauth'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.userlogout, name='logout'),
    path('register/', views.userregister, name='register'),
]

templates/navbar.html
<!DOCTYPE html>
<html>

{% load static %}

    <head>
        <title>{% block title %}{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styling/style.css' %}">

        {% block head %}
        {% endblock head %}
        <style>
            {% block styling %}
            {% endblock styling %}
        </style>
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="padding: 0;">
            <a class="navbar-brand my-title">TK2 - A11</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                    </li>
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'faq:index' %}">FAQ</a>
                    </li>
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'hoaxbuster:index' %}">Hoax Buster</a>
                    </li>
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'penanganan:index' %}">Penanganan</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'userauth:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item my-nav">
                        <a class="nav-link" href="{% url 'userauth:index' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 

        {% block script %}
        {% endblock script %}
        
    </body>
</html>

templates/template.html
{% extends 'navbar.html' %}

{% block content %}
<div class="container-fluid px-0">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner bg-info" role="listbox">
            <div class="carousel-item active">
                <a href="{% url 'home:index' %}">
                    <div class="d-flex align-items-center justify-content-center min-vh-100">
                        <img src="/static/img/home.png" class="slider-pic">
                        <div class="slider-info">
                            <h1 class="slider-title">Home Page</h1>
                            <h4 class="slider-text">Lihat informasi terkini tentang kasus COVID-19</h4>
                        </div>
                    </div>
                </a>
            </div>
            <div class="carousel-item">
                <a href="{% url 'faq:index' %}">
                    <div class="d-flex align-items-center justify-content-center min-vh-100">
                        <div class="slider-info" style="text-align: right;">
                            <h1 class="slider-title">Frequently Asked Question</h1>
                            <h4 class="slider-text">Pertanyaan yang sering muncul seputar COVID-19</h4>
                        </div>
                        <img src="/static/img/faq.png" class="slider-pic">
                    </div>
                </a>
            </div>
            <div class="carousel-item">
                <a href="{% url 'hoaxbuster:index' %}">
                    <div class="d-flex align-items-center justify-content-center min-vh-100">
                        <img src="/static/img/hoaxbuster.png" class="slider-pic">
                        <div class="slider-info">
                            <h1 class="slider-title">Hoax Buster</h1>
                            <h4 class="slider-text">Ketahui kebenaran dari hoax yang umum beredar di masyarakat</h4>
                        </div>
                    </div>
                </a>
            </div>
            <div class="carousel-item">
                <a href="{% url 'penanganan:index' %}">
                    <div class="d-flex align-items-center justify-content-center min-vh-100">
                        <div class="slider-info" style="text-align: right;">
                            <h1 class="slider-title">Penanganan</h1>
                            <h4 class="slider-text">Informasi penanganan COVID-19 berdasarkan situasi dan kondisi</h4>
                        </div>
                        <img src="/static/img/penanganan.png" class="slider-pic">
                    </div>
                </a>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

{% block body %}
{% endblock body %}

<footer class="page-footer font-small bg-info">
    <div class="footer-text text-center py-3">
        Made by Kelompok A11
    </div>
</footer>

{% endblock content %}